### Урок 6. Взаимосвязь величин. Параметрические и непараметрические показатели корреляции. Корреляционный анализ.


In [1]:
import numpy as np

#### 1. Даны значения величины заработной платы заемщиков банка (zp) и значения их поведенческого кредитного скоринга (ks):

zp = [35, 45, 190, 200, 40, 70, 54, 150, 120, 110],

ks = [401, 574, 874, 919, 459, 739, 653, 902, 746, 832].

#### Найдите ковариацию этих двух величин с помощью элементарных действий, а затем с помощью функции cov из numpy Полученные значения должны быть равны. 
####  Найдите коэффициент корреляции Пирсона с помощью ковариации и среднеквадратичных отклонений двух признаков, а затем с использованием функций из библиотек numpy и pandas.

In [2]:
zp = np.array([35, 45, 190, 200, 40, 70, 54, 150, 120, 110])
ks = np.array([401, 574, 874, 919, 459, 739, 653, 902, 746, 832])

In [3]:
cov = np.mean(zp*ks)-np.mean(zp)*np.mean(ks)
cov

9157.839999999997

In [4]:
cov = np.cov(zp,ks,ddof=0)
cov

array([[ 3494.64,  9157.84],
       [ 9157.84, 30468.89]])

In [5]:
cor = cov / (np.std(zp, ddof=0)*np.std(ks, ddof=0))
cor

array([[0.33866702, 0.88749009],
       [0.88749009, 2.95275283]])

In [6]:
cor2 = np.corrcoef(zp,ks)
cor2

array([[1.        , 0.88749009],
       [0.88749009, 1.        ]])

#### 2. Измерены значения IQ выборки студентов, обучающихся в местных технических вузах:

131, 125, 115, 122, 131, 115, 107, 99, 125, 111

#### Известно, что в генеральной совокупности IQ распределен нормально. Найдите доверительный интервал для математического ожидания с надежностью 0.95.

In [7]:
data = np.array([131, 125, 115, 122, 131, 115, 107, 99, 125, 111])
n = len(data)
t = 2.262
std = np.std(data, ddof=1)
mu = data.mean()

In [8]:
L = mu - t * std / n**0.5
U = mu + t * std / n**0.5
print(f'Ответ: [{L}; {U}]')

Ответ: [110.55660776308164; 125.64339223691834]


#### 3. Известно, что рост футболистов в сборной распределен нормально с дисперсией генеральной совокупности, равной 25 кв.см. Объем выборки равен 27, среднее выборочное составляет 174.2. Найдите доверительный интервал для математического ожидания с альфа =0,95

In [9]:
std = 25**0.5
X = 174.2
n = 27
Z = 1.96

In [10]:
L = X - Z * std / n**0.5
U = X + Z * std / n**0.5
print(f'Ответ: [{L}; {U}]')

Ответ: [172.31398912064722; 176.08601087935276]
